# SK

web:
  container_name: ft-demo-website
  build: .
  ports:
   - 80:80
  volumes:
     - /var/www/html/
db:
  image: mysql:5.7
  container_name: mysql
  volumes:
   - /var/lib/mysql
  restart: always
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: ftdemowebsite
   MYSQL_DATABASE: ftdemowebsite
   MYSQL_USER: ftdemowebsite
   MYSQL_PASSWORD: ftdemowebsite
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
   - PMA_ARBITRARY=1
  restart: always
  ports:
   - 8081:80
  volumes:
   - /sessions
